apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kubernetes-django-deployment
  labels:
    app: kubernetes-django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-django
  template:
    metadata:
      labels: 
        app: kubernetes-django
    spec:
      containers:
        - name: kubernetes-django
          image: gitumarkk/k8_django_minikube:1.0.5
          ports:
            - containerPort: 8000